name: Simple-Actions

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: List and Read files
          run: |
            echo "First Github Avtions Job"
            ls -lrt
            cat README.md

        - name: Generate cowsay
          run: cowsay -f dragon "Dragon... Artwork" >> dragon.txt

        - name: Test and Read
          run: |
            grep -i "dragon" dragon.txt
            cat dragon.txt
